// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UROEOv_onMiLspokTXkZh-MgSYnjWAM',
    appId: '1:353895097532:web:f7da6a47df74f8f7895cb9',
    messagingSenderId: '353895097532',
    projectId: 'welcome-bbf26',
    authDomain: 'welcome-bbf26.firebaseapp.com',
    storageBucket: 'welcome-bbf26.firebasestorage.app',
    measurementId: 'G-JX5BRJ8W0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGD7Xn4P1Bz072mkFc0FEZ7JMy0nFXFrE',
    appId: '1:353895097532:android:9ab8ec2677826dad895cb9',
    messagingSenderId: '353895097532',
    projectId: 'welcome-bbf26',
    storageBucket: 'welcome-bbf26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJt5yWmdFoXw-eigiutcJ1X9Q2GAtEImo',
    appId: '1:353895097532:ios:9a032d92b219722b895cb9',
    messagingSenderId: '353895097532',
    projectId: 'welcome-bbf26',
    storageBucket: 'welcome-bbf26.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJt5yWmdFoXw-eigiutcJ1X9Q2GAtEImo',
    appId: '1:353895097532:ios:9a032d92b219722b895cb9',
    messagingSenderId: '353895097532',
    projectId: 'welcome-bbf26',
    storageBucket: 'welcome-bbf26.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5UROEOv_onMiLspokTXkZh-MgSYnjWAM',
    appId: '1:353895097532:web:72033eed513499d7895cb9',
    messagingSenderId: '353895097532',
    projectId: 'welcome-bbf26',
    authDomain: 'welcome-bbf26.firebaseapp.com',
    storageBucket: 'welcome-bbf26.firebasestorage.app',
    measurementId: 'G-RWVMWL0298',
  );
}
